=== Daniel-RodriguezFernandez/SEW/xml/circuito.dtd
<!ELEMENT circuito (
  nombre, 
  distancia, 
  anchuraMedia, 
  fechaCarrera, 
  horaInicio, 
  numeroVueltas, 
  localidad, 
  pais, 
  patrocinador, 
  referencias, 
  galeriaFotos, 
  galeriaVideos, 
  origenCircuito, 
  puntosAnonimo, 
  vencedor, 
  clasificacion
)>

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidad (m) #REQUIRED>

<!ELEMENT anchuraMedia (#PCDATA)>
<!ATTLIST anchuraMedia unidad (m) #REQUIRED>

<!ELEMENT fechaCarrera (#PCDATA)>
<!ELEMENT horaInicio (#PCDATA)>
<!ELEMENT numeroVueltas (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT patrocinador (#PCDATA)>

<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>

<!ELEMENT galeriaFotos (foto+)>
<!ELEMENT foto EMPTY>
<!ATTLIST foto src CDATA #REQUIRED alt CDATA #REQUIRED>

<!ELEMENT galeriaVideos (video+)>
<!ELEMENT video EMPTY>
<!ATTLIST video src CDATA #REQUIRED>

<!ELEMENT origenCircuito (latitud, longitud, altitud)>

<!ELEMENT latitud (#PCDATA)>
<!ATTLIST latitud unidad (grados) #REQUIRED>

<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud unidad (grados) #REQUIRED>

<!ELEMENT altitud (#PCDATA)>
<!ATTLIST altitud unidad (m) #REQUIRED>

<!ELEMENT puntosAnonimos (puntoAnonimo+)> 

<!ELEMENT puntoAnonimo (nombre, distancia, latitud, longitud, altitud, sector)>
<!ELEMENT sector (#PCDATA)>

<!ELEMENT vencedor EMPTY>
<!ATTLIST vencedor nombre CDATA #REQUIRED tiempo CDATA #REQUIRED>

<!ELEMENT clasificacion (piloto+)>
<!ELEMENT piloto EMPTY>
<!ATTLIST piloto posicion CDATA #REQUIRED nombre CDATA #REQUIRED>

=== Daniel-RodriguezFernandez/SEW/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<circuito>
  <nombre>Circuit Ricardo Tormo</nombre>
  <distancia unidad="m">4005</distancia>
  <anchuraMedia unidad="m">12</anchuraMedia>
  <fechaCarrera>16/11</fechaCarrera>
  <horaInicio>14:00</horaInicio>
  <numeroVueltas>30</numeroVueltas>
  <localidad>Cheste</localidad>
  <pais>Espa√±a</pais>
  <patrocinador>Comunitat Valenciana</patrocinador>

  <referencias>
    <referencia>https://www.circuitricardotormo.com/</referencia>
    <referencia>https://es.wikipedia.org/wiki/Circuito_Ricardo_Tormo</referencia>
    <referencia>https://www.instagram.com/circuitvalencia/?hl=en</referencia>
  </referencias>
  
  <galeriaFotos>
    <foto src="multimedia\circuito.png" alt="Mapa del circuito"/>
  </galeriaFotos>
  
  <galeriaVideos>
    <video src="multimedia\circuito.mp4"/>
  </galeriaVideos>
  
  <origenCircuito>
    <latitud unidad="grados">39.4833</latitud>
    <longitud unidad="grados">-0.6308</longitud>
    <altitud unidad="m">154</altitud>
  </origenCircuito>
  
  <puntosAnonimos>
    <!-- Sector 1 -->
    <puntoAnonimo>
        <distancia unidad="m">18.37</distancia>
        <latitud unidad="grados">39.48165352113205</latitud>
        <longitud unidad="grados">-0.634960789505522</longitud>
        <altitud unidad="m">159.13070622706</altitud>
        <sector>1</sector>
    </puntoAnonimo>
    <puntoAnonimo>
        <distancia unidad="m">29.4</distancia>
        <latitud unidad="grados">39.48164800747235</latitud>
        <longitud unidad="grados">-0.6346251439095252</longitud>
        <altitud unidad="m">158.2852204952856</altitud>
        <sector>1</sector>
    </puntoAnonimo>
    <puntoAnonimo>
        <distancia unidad="m">861.14</distancia>
        <latitud unidad="grados">39.4860596040287</latitud>
        <longitud unidad="grados">-0.626357408073811</longitud>
        <altitud unidad="m">146.5443370856989</altitud>
        <sector>1</sector>
    </puntoAnonimo>

    <!-- Sector 2 -->
    <puntoAnonimo>
        <distancia unidad="m">43.66</distancia>
        <latitud unidad="grados">39.48639887693418</latitud>
        <longitud unidad="grados">-0.6260697906951174</longitud>
        <altitud unidad="m">146.2847484580939</altitud>
        <sector>2</sector>
    </puntoAnonimo>
    <puntoAnonimo>
        <distancia unidad="m">34.33</distancia>
        <latitud unidad="grados">39.486721437127</latitud>
        <longitud unidad="grados">-0.6260537471805605</longitud>
        <altitud unidad="m">146.2372892663496</altitud>
        <sector>2</sector>
    </puntoAnonimo>
    <puntoAnonimo>
        <distancia unidad="m">318.19</distancia>
        <latitud unidad="grados">39.48936736956964</latitud>
        <longitud unidad="grados">-0.6274612774286947</longitud>
        <altitud unidad="m">151.5412123891565</altitud>
        <sector>2</sector>
    </puntoAnonimo>

    <!-- Sector 3 -->
    <puntoAnonimo>
        <distancia unidad="m">23.94</distancia>
        <latitud unidad="grados">39.48944011088887</latitud>
        <longitud unidad="grados">-0.6277512361645665</longitud>
        <altitud unidad="m">151.6477172112768</altitud>
        <sector>3</sector>
    </puntoAnonimo>
    <puntoAnonimo>
        <distancia unidad="m">23.28</distancia>
        <latitud unidad="grados">39.4893111080541</latitud>
        <longitud unidad="grados">-0.6280173086590635</longitud>
        <altitud unidad="m">152.0788481336951</altitud>
        <sector>3</sector>
    </puntoAnonimo>

    <!-- Sector 4 -->
    <puntoAnonimo>
        <distancia unidad="m">139.43</distancia>
        <latitud unidad="grados">39.48805440996832</latitud>
        <longitud unidad="grados">-0.6282843701254648</longitud>
        <altitud unidad="m">151.4762011171666</altitud>
        <sector>4</sector>
    </puntoAnonimo>
    <puntoAnonimo>
        <distancia unidad="m">157.44</distancia>
        <latitud unidad="grados">39.4869051711397</latitud>
        <longitud unidad="grados">-0.6271502823121056</longitud>
        <altitud unidad="m">148.5673999203166</altitud>
        <sector>4</sector>
    </puntoAnonimo>

    <!-- Sector 5 -->
    <puntoAnonimo>
        <distancia unidad="m">28.21</distancia>
        <latitud unidad="grados">39.48665283012605</latitud>
        <longitud unidad="grados">-0.6271626024843879</longitud>
        <altitud unidad="m">148.3223774986317</altitud>
        <sector>5</sector>
    </puntoAnonimo>
    <puntoAnonimo>
        <distancia unidad="m">126.43</distancia>
        <latitud unidad="grados">39.48601710907781</latitud>
        <longitud unidad="grados">-0.6283850147499193</longitud>
        <altitud unidad="m">149.0521549293201</altitud>
        <sector>5</sector>
    </puntoAnonimo>

    <!-- Sector 6 -->
    <puntoAnonimo>
        <distancia unidad="m">41.98</distancia>
        <latitud unidad="grados">39.48609731891976</latitud>
        <longitud unidad="grados">-0.6288738299502961</longitud>
        <altitud unidad="m">149.7129146481429</altitud>
        <sector>6</sector>
    </puntoAnonimo>
    <puntoAnonimo>
        <distancia unidad="m">34.78</distancia>
        <latitud unidad="grados">39.48636374466233</latitud>
        <longitud unidad="grados">-0.6290896334493667</longitud>
        <altitud unidad="m">150.0023500496631</altitud>
        <sector>6</sector>
    </puntoAnonimo>
    <puntoAnonimo>
        <distancia unidad="m">215.02</distancia>
        <latitud unidad="grados">39.48829861273209</latitud>
        <longitud unidad="grados">-0.6291251604204318</longitud>
        <altitud unidad="m">154.7368322105294</altitud>
        <sector>6</sector>
    </puntoAnonimo>

    <!-- Sector 7 -->
    <puntoAnonimo>
        <distancia unidad="m">29.01</distancia>
        <latitud unidad="grados">39.48848245427408</latitud>
        <longitud unidad="grados">-0.6293520461913227</longitud>
        <altitud unidad="m">155.4794646629715</altitud>
        <sector>7</sector>
    </puntoAnonimo>
    <puntoAnonimo>
        <distancia unidad="m">32.85</distancia>
        <latitud unidad="grados">39.48851753833272</latitud>
        <longitud unidad="grados">-0.62973226900084</longitud>
        <altitud unidad="m">156.527793045826</altitud>
        <sector>7</sector>
    </puntoAnonimo>

    <!-- Sector 8 -->
    <puntoAnonimo>
        <distancia unidad="m">306.44</distancia>
        <latitud unidad="grados">39.48694709412071</latitud>
        <longitud unidad="grados">-0.6326627345381919</longitud>
        <altitud unidad="m">162.4346427946614</altitud>
        <sector>8</sector>
    </puntoAnonimo>
    <puntoAnonimo>
        <distancia unidad="m">175</distancia>
        <latitud unidad="grados">39.48558348625532</latitud>
        <longitud unidad="grados">-0.6336777053887177</longitud>
        <altitud unidad="m">163.1184108232847</altitud>
        <sector>8</sector>
    </puntoAnonimo>
    <puntoAnonimo>
        <distancia unidad="m">31.86</distancia>
        <latitud unidad="grados">39.48530281784014</latitud>
        <longitud unidad="grados">-0.6336316423033816</longitud>
        <altitud unidad="m">162.1777101114238</altitud>
        <sector>8</sector>
    </puntoAnonimo>

    <!-- Sector 9 -->
    <puntoAnonimo>
        <distancia unidad="m">35.64</distancia>
        <latitud unidad="grados">39.48508349310853</latitud>
        <longitud unidad="grados">-0.6333293901689907</longitud>
        <altitud unidad="m">161.0603529414214</altitud>
        <sector>9</sector>
    </puntoAnonimo>
    <puntoAnonimo>
        <distancia unidad="m">23.28</distancia>
        <latitud unidad="grados">39.48508309052805</latitud>
        <longitud unidad="grados">-0.6328554578528589</longitud>
        <altitud unidad="m">159.333133120049</altitud>
        <sector>9</sector>
    </puntoAnonimo>

    <!-- Sector 10 -->
    <puntoAnonimo>
        <distancia unidad="m">38.98</distancia>
        <latitud unidad="grados">39.48575102329369</latitud>
        <longitud unidad="grados">-0.6316652290151403</longitud>
        <altitud unidad="m">156.4841417565425</altitud>
        <sector>10</sector>
    </puntoAnonimo>

    <!-- Sector 11 -->
    <puntoAnonimo>
        <distancia unidad="m">23.94</distancia>
        <latitud unidad="grados">39.48682413580035</latitud>
        <longitud unidad="grados">-0.6313010633715999</longitud>
        <altitud unidad="m">156.4449072513663</altitud>
        <sector>11</sector>
    </puntoAnonimo>
    <puntoAnonimo>
        <distancia></distancia>
        <latitud unidad="grados">39.48730184924943</latitud>
        <longitud unidad="grados">-0.6304834591532715</longitud>
        <altitud unidad="m">155.7254225520321</altitud>
        <sector>11</sector>
    </puntoAnonimo>
    <puntoAnonimo>
        <distancia></distancia>
        <latitud unidad="grados">39.48729299688833</latitud>
        <longitud unidad="grados">-0.6301542548215067</longitud>
        <altitud unidad="m">155.4861923388968</altitud>
        <sector>11</sector>
    </puntoAnonimo>

    <!-- Sector 12 -->
    <puntoAnonimo>
        <distancia></distancia>
        <latitud unidad="grados">39.48710477165429</latitud>
        <longitud unidad="grados">-0.6299350078865595</longitud>
        <altitud unidad="m">154.9453005179446</altitud>
        <sector>12</sector>
    </puntoAnonimo>
    <puntoAnonimo>
        <distancia></distancia>
        <latitud unidad="grados">39.48691776071102</latitud>
        <longitud unidad="grados">-0.6299376415034941</longitud>
        <altitud unidad="m">154.6962616152097</altitud>
        <sector>12</sector>
    </puntoAnonimo>

    <!-- Sector 13 -->
    <puntoAnonimo>
        <distancia></distancia>
        <latitud unidad="grados">39.48456376553231</latitud>
        <longitud unidad="grados">-0.6317642604807983</longitud>
        <altitud unidad="m">156.4367331526249</altitud>
        <sector>13</sector>
    </puntoAnonimo>
    <puntoAnonimo>
        <distancia></distancia>
        <latitud unidad="grados">39.48453395140052</latitud>
